# Generated by Django 3.1.1 on 2020-09-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20200923_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default/category_image.jpg', upload_to='product/category/images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('unit_price', models.IntegerField()),
                ('unit_mrp', models.IntegerField()),
                ('is_adult', models.BooleanField(default=False)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='default/product_image.jpg', upload_to='product/product/images/')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.seller')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('C', 'Color'), ('S', 'Size'), ('U', 'Units')], default='', max_length=1)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_available', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/variant/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='product.Tag'),
        ),
    ]
