# Generated by Django 3.1.1 on 2020-09-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default/user_image.jpg', upload_to='user/customuser/images/'),
        ),
    ]
