# Generated by Django 3.1.1 on 2020-09-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='aadhar_no',
            field=models.CharField(default=2222, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='pan_no',
            field=models.CharField(default=2222, max_length=10),
            preserve_default=False,
        ),
    ]
