# Generated by Django 3.1.1 on 2020-10-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_seller_amount_for_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_phone_verified',
        ),
    ]
