# Generated by Django 3.1.1 on 2020-10-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201020_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bank_account_bearers_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Bank Account bearer's name"),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Branch Name'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Bank IFSC Code'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='upi_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='UPI Address'),
        ),
    ]
