# Generated by Django 3.1.1 on 2020-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201015_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
