# Generated by Django 3.1.1 on 2020-10-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201017_2146'),
        ('user', '0007_seller_amount_for_delivered'),
        ('order', '0012_auto_20201017_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variant')),
            ],
        ),
    ]
